<?php
CREATE TABLE MASTER_USER_CONFIG( 
    _id INT NOT NULL AUTO_INCREMENT, 
    ACCOUNT_NAME VARCHAR(128) NOT NULL, 
    SNAPS_SAVE_DIR_VIDEO VARCHAR(128), 
    SNAPS_SAVE_DIR_PICTURE VARCHAR(128), 
    PRIMARY KEY ( _id ) 
);



?>
